### ISSUE TITLE
Support multiple search results

### ISSUE THREAD

**Issue by austinberke** [nfischer/framily-tree#11]
Problem:
- Typing in a query that matches multiple brothers will only return one result based on first match of `nodes.find()`

Proposed solution:
- Populate list of all matches within nodes using `nodes.filter()`
- Show indicator of multiple matches near search box
- Add `Next` button or hit Enter to cycle through all results

**Comment by nfischer** [comment]
I wonder, is this necessary? For example, if I search for `nick` and get the wrong one, I'll usually type in a last name. Do you have a scenario in mind for where my approach wouldn't be as natural a response?

**Comment by austinberke** [comment]
It's not super high priority, but my issue with it is a matter of defined behavior: it seems `nodes.find()` will return an arbitrary match which doesn't seem like the best practice for a search function.

**Comment by nfischer** [comment]
Fair point. Maybe after we change the internals to return multiple search results, we could score and order the results. Currently, sometimes the returned result isn't the best one (e.g., "jose" points to "**Jose**ph Dominguez).
